# Generated by Django 2.0.5 on 2018-11-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='CR',
            field=models.FloatField(help_text='compression ratio'),
        ),
        migrations.AlterField(
            model_name='version',
            name='ICWT',
            field=models.IntegerField(help_text='°C intercooler water temperature'),
        ),
        migrations.AlterField(
            model_name='version',
            name='NOx_emission',
            field=models.IntegerField(help_text='mg/m3'),
        ),
        migrations.AlterField(
            model_name='version',
            name='electrical_efficiency',
            field=models.FloatField(help_text='%'),
        ),
        migrations.AlterField(
            model_name='version',
            name='electrical_output',
            field=models.IntegerField(help_text='kW'),
        ),
        migrations.AlterField(
            model_name='version',
            name='energy_input',
            field=models.IntegerField(help_text='kW'),
        ),
        migrations.AlterField(
            model_name='version',
            name='engine_speed',
            field=models.IntegerField(help_text='rpm'),
        ),
        migrations.AlterField(
            model_name='version',
            name='mechanical_output',
            field=models.IntegerField(help_text='kW'),
        ),
        migrations.AlterField(
            model_name='version',
            name='thermal_efficiency',
            field=models.FloatField(help_text='%'),
        ),
        migrations.AlterField(
            model_name='version',
            name='thermal_output',
            field=models.IntegerField(help_text='kW'),
        ),
        migrations.AlterField(
            model_name='version',
            name='total_efficiency',
            field=models.FloatField(help_text='%'),
        ),
    ]
