# Generated by Django 2.0.5 on 2018-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0002_auto_20181114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('NG', 'Natural gas'), ('BL', 'Biogas/sewage gas/landfill gas'), ('APG', 'Flaregas'), ('CG', 'Coalmine gas'), ('HD', 'HD-5 Propane')], default='NG', max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, choices=[('Jenbacher', 'Jenbacher'), ('Waukesha', 'Waukesha'), ('Siemens', 'Siemens'), ('Solar', 'Solar')], default='Jenbacher', max_length=100),
        ),
    ]
