# Generated by Django 2.0.5 on 2018-11-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0003_auto_20181114_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(50, '50Hz'), (60, '60Hz')], default=50)),
                ('NOx', models.CharField(choices=[('ultralow', '<50mg/m3'), ('low', '<250mg/m3'), ('middle', '<500mg/m3'), ('high', '>500mg/m3')], default='middle', max_length=100)),
                ('gas_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enginedata.Genre')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enginedata.Manufacturer')),
            ],
            options={
                'ordering': ['gas_type__name', 'version__electrical_output'],
            },
        ),
        migrations.RemoveField(
            model_name='engineversions',
            name='gas_type',
        ),
        migrations.RemoveField(
            model_name='engineversions',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='engineversions',
            name='version',
        ),
        migrations.RenameModel(
            old_name='Version',
            new_name='Technicaldata',
        ),
        migrations.DeleteModel(
            name='EngineVersions',
        ),
        migrations.AddField(
            model_name='moduleversion',
            name='version',
            field=models.OneToOneField(help_text='Module version number', on_delete=django.db.models.deletion.CASCADE, to='enginedata.Technicaldata'),
        ),
    ]
