# Generated by Django 2.0.5 on 2018-11-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0004_auto_20181115_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicaldata',
            options={'ordering': ['electrical_output']},
        ),
    ]
