# Generated by Django 2.0.5 on 2018-11-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0007_auto_20181115_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('Natural gas', 'Natural gas'), ('Biogas', 'Biogas'), ('Sewage gas', 'Sewage gas'), ('Landfill gas', 'Landfill gas'), ('Flaregas', 'Flaregas'), ('Coalmine gas', 'Coalmine gas'), ('HD-5 Propane', 'HD-5 Propane')], default='Natural gas', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicaldata',
            name='fuel_gas_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enginedata.Genre'),
        ),
    ]
