# Generated by Django 2.0.5 on 2018-11-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0008_auto_20181115_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldata',
            name='fuel_gas_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enginedata.Genre'),
        ),
    ]
