# Generated by Django 2.0.5 on 2018-11-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0009_auto_20181115_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldata',
            name='fuel_gas_type',
            field=models.CharField(choices=[('NG', 'Natural gas'), ('BG', 'Biogas'), ('SG', 'Sewage gas'), ('LG', 'Landfill gas'), ('APG', 'Flaregas'), ('CG', 'Coalmine gas'), ('HD', 'HD-5 Propane')], default='NG', max_length=100),
        ),
    ]
