# Generated by Django 2.0.5 on 2018-11-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enginedata', '0012_auto_20181120_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricusedata',
            name='projectname',
        ),
        migrations.DeleteModel(
            name='FuelUseData',
        ),
        migrations.DeleteModel(
            name='ThermalLoads',
        ),
        migrations.DeleteModel(
            name='ElectricUseData',
        ),
        migrations.DeleteModel(
            name='SiteData',
        ),
    ]
